### ISSUE TITLE
Validate feature metadata

### ISSUE THREAD

**Issue by emarx** [chalk-ai/roadmap#19]
For some features, it is important to specify metadata such as owner and description. Chalk allows you to enforce metadata requirement easily. In addition, you can specify for each feature the severity at which to raise a missing metadata issue.

```yaml
project: 'Predict Q2 Spending'

validation:
  feature:
    metadata:
      - name: owner
        missing: error
      - name: description
        missing: warning
      - name: tags
        missing: info

environments:
  default:
    runtimes: 'python310'
    requirements: requirements.txt
    dockerfile: null
```
See the docs at: https://docs.chalk.ai/docs/validation
